
variable "do_token" {
    type	                 = string
    description	           = "String, DigitalOcean API token"
    default                = ""
}


variable "cloudflare_api_token" {
    type	                 = string
    description	           = "String, API token generated by CloudFlare"
    default                = ""
}

variable "ssh_fingerprint" {
    type	                 = string
    description	           = "String, fingerprint of the SSH public key to be used for authenticating login to the new instances"
    default                = ""
}

variable "cluster_postfix" {
    type	                 = string
    description	           = "String, it is added to the end of the name of VMs and Volumes just before the index number"
    default                = ""
}

variable "monitoring" {
    type	                 = bool
    description	           = "Boolean, enables/disables the DigitalOcean monitoring functionality"
    default                = "false"
}

variable "cloudflare_subdomain" {
    type                   = string
    description            = "String, an optional subdomain for the cloudFlare DNS zone"
    default                = ""
}

variable "cloudflare_zone" {
    type                   = string
    description            = "String, the DNS zone for the new records"
    default                = "example.com"
}

variable "private_networking" {
    type	                 = bool
    description	           = "Boolean, enable/disable private networking"
    default                = "false"
}

variable "cluster_prefix" {
    type	                 = string
    description	           = "String, it is added to the beginning of the name of VMs and Volumes"
    default                = ""
}

variable "pvt_key" {
    type	                 = string
    description	           = "String, it's the path to the private key used to connect to the remote instances"
    default                = ""
}

#variable "admin_password" {
#    type                   = string
#    description            = "Password for sudo account on remote instances"
#}
